=== stevenvanrossem/un-orchestrator/virtualizer/config/universal-node-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- definition of attributes -->

<xsd:attribute name="port-type">	
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="port-abstract"/>
			<xsd:enumeration value="port-sap"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:attribute>


<!-- definition of elements -->
<xsd:element name="universal-node">
	<xsd:complexType>
		<xsd:all>
		
			<xsd:element name="ports" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>				
					
						<xsd:element name="port" minOccurs="0" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
						
									<xsd:element name="virtualized" minOccurs="1" maxOccurs="1">
										<xsd:complexType>
											<xsd:attribute name="as" type="xsd:string" use="required"/>
											<xsd:attribute ref="port-type" use="required"/>
											<xsd:attribute name="sap" type="xsd:string"/>
										</xsd:complexType>
									</xsd:element> <!-- End <virtualized> -->
																		
								</xsd:sequence>
								
								<xsd:attribute name="name" type="xsd:string" use="required"/>
								
							</xsd:complexType>
						</xsd:element> <!-- End <element> -->
						
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element> <!-- End <ports> -->
	
		</xsd:all>
	</xsd:complexType>
		
	<xsd:unique name="unique-physical-port">
		<xsd:selector xpath="physical-ports/port" />
		<xsd:field xpath="@name" />
	</xsd:unique>
	<!-- TODO: the "as" attribute must be unique! -->
	
</xsd:element>

</xsd:schema>

=== stevenvanrossem/un-orchestrator/orchestrator/config/universal-node-er-demo.xml
<?xml version="1.0" encoding="UTF-8"?>

<universal-node xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                 xsi:noNamespaceSchemaLocation="universal-node-schema.xsd">

	<ports>
		<port name="veth0un" type="ethernet" side="edge">
			<virtualized as="virtual-sap1" port-type="port-sap" sap="sap1"/>
		</port>
		<port name="veth1un" type="ethernet" side="edge">
			<virtualized as="virtual-sap2" port-type="port-sap" sap="sap2"/>
		</port>
		<port name="veth2un" type="ethernet" side="edge">
			<virtualized as="virtual-sap3" port-type="port-sap" sap="sap3"/>
		</port>
		<port name="veth3un" type="ethernet" side="edge">
			<virtualized as="virtual-sap4" port-type="port-sap" sap="sap4"/>
		</port>
		
		<!-- 
			Values for "port-type":
			* port-abstract
			* port-type
		-->	
		
	</ports>	

</universal-node>
